swagger: "2.0"
info:
  title: CSI TASK-1 CRUD API
  description: This documentation is regarding the task-1 of Celebal Summer Intern in domain of nodeJS
  version: 1.0
  contact:
    email: divyaanshmertia@gmail.com
  servers:
    -url: http://localhost:9160/
    description: This is my local Server
    

schemes: [http,https]    

paths: 
  /:
    get:
      summary: Hello World.
      description: this api is used to say hello to user.
      responses:
        200:
          description: To test Get method.